package com.hebabr.base.dao;

import com.hebabr.model.EntidadeDto;
import com.hebabr.model.EntidadeDtoExample;
import java.util.List;

import org.springframework.stereotype.Repository;


@Repository
public interface EntidadeDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entidade
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    long countByExample(EntidadeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entidade
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entidade
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    int insert(EntidadeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entidade
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    int insertSelective(EntidadeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entidade
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    List<EntidadeDto> selectByExample(EntidadeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entidade
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    EntidadeDto selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entidade
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    int updateByPrimaryKeySelective(EntidadeDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entidade
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    int updateByPrimaryKey(EntidadeDto record);
}