package com.hebabr.model;

public class EntidadeDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entidade.id
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entidade.atributo
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    private String atributo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entidade.id
     *
     * @return the value of entidade.id
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entidade.id
     *
     * @param id the value for entidade.id
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entidade.atributo
     *
     * @return the value of entidade.atributo
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    public String getAtributo() {
        return atributo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entidade.atributo
     *
     * @param atributo the value for entidade.atributo
     *
     * @mbg.generated Tue Nov 07 08:29:29 CST 2017
     */
    public void setAtributo(String atributo) {
        this.atributo = atributo;
    }
}